-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."AdviceCache"
(
    advice_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    generated_time timestamp with time zone NOT NULL,
    advice_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    message_vi text COLLATE pg_catalog."default" NOT NULL,
    location_id bigint NOT NULL,
    CONSTRAINT "AdviceCache_pkey" PRIMARY KEY (advice_id)
);

CREATE TABLE IF NOT EXISTS public."DeviceTokens"
(
    token_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT "DeviceTokens_pkey" PRIMARY KEY (token_id),
    CONSTRAINT "DeviceTokens_token_key" UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public."ExtremeEvents"
(
    event_id bigserial NOT NULL,
    location_id bigint,
    analysis_time timestamp with time zone NOT NULL DEFAULT now(),
    severity character varying(20) COLLATE pg_catalog."default" NOT NULL,
    impact_field character varying(50) COLLATE pg_catalog."default" NOT NULL,
    forecast_details_vi text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    is_notified boolean DEFAULT false,
    raw_llm_json jsonb,
    actionable_advice_vi text COLLATE pg_catalog."default",
    CONSTRAINT "ExtremeEvents_pkey" PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS public."LocationNotificationPreferences"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    notifications_enabled boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    location_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT "LocationNotificationPreferences_pkey" PRIMARY KEY (id),
    CONSTRAINT "LocationNotificationPref_user_id_location_id_e98ddc1d_uniq" UNIQUE (user_id, location_id)
);

CREATE TABLE IF NOT EXISTS public."Locations"
(
    location_id bigserial NOT NULL,
    name_en character varying(100) COLLATE pg_catalog."default" NOT NULL,
    latitude numeric(10, 6) NOT NULL,
    longitude numeric(10, 6) NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    users jsonb,
    last_weather_check timestamp with time zone,
    last_weather_condition character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT "Locations_pkey" PRIMARY KEY (location_id),
    CONSTRAINT "Locations_name_en_key" UNIQUE (name_en)
);

CREATE TABLE IF NOT EXISTS public."NotificationPreferences"
(
    preference_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    enabled_event_types jsonb NOT NULL,
    notification_schedule character varying(20) COLLATE pg_catalog."default" NOT NULL,
    morning_summary_enabled boolean NOT NULL,
    tomorrow_forecast_enabled boolean NOT NULL,
    weekly_summary_enabled boolean NOT NULL,
    timezone character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    notifications_enabled boolean NOT NULL,
    CONSTRAINT "NotificationPreferences_pkey" PRIMARY KEY (preference_id)
);

CREATE TABLE IF NOT EXISTS public."NotificationRecords"
(
    record_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    notification_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default" NOT NULL,
    priority character varying(20) COLLATE pg_catalog."default" NOT NULL,
    sent_at timestamp with time zone NOT NULL,
    delivered boolean NOT NULL,
    fcm_message_id character varying(255) COLLATE pg_catalog."default",
    location_id bigint,
    user_id bigint NOT NULL,
    alert_id bigint,
    CONSTRAINT "NotificationRecords_pkey" PRIMARY KEY (record_id)
);

CREATE TABLE IF NOT EXISTS public."PreferenceAuditLogs"
(
    log_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    preference_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    field_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    old_value jsonb,
    new_value jsonb,
    changed_at timestamp with time zone NOT NULL,
    ip_address inet,
    user_agent text COLLATE pg_catalog."default",
    location_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT "PreferenceAuditLogs_pkey" PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public."QueuedNotifications"
(
    queue_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    notification_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default" NOT NULL,
    priority character varying(20) COLLATE pg_catalog."default" NOT NULL,
    data jsonb NOT NULL,
    scheduled_for timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    sent boolean NOT NULL,
    location_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT "QueuedNotifications_pkey" PRIMARY KEY (queue_id)
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    user_id bigserial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT "Users_pkey" PRIMARY KEY (user_id),
    CONSTRAINT "Users_username_key" UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public."WeatherAlerts"
(
    alert_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    alert_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    severity character varying(20) COLLATE pg_catalog."default" NOT NULL,
    detected_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    is_active boolean NOT NULL,
    title_vi character varying(200) COLLATE pg_catalog."default" NOT NULL,
    message_vi text COLLATE pg_catalog."default" NOT NULL,
    recommended_actions text COLLATE pg_catalog."default",
    weather_data jsonb NOT NULL,
    location_id bigint NOT NULL,
    CONSTRAINT "WeatherAlerts_pkey" PRIMARY KEY (alert_id)
);

CREATE TABLE IF NOT EXISTS public."WeatherData"
(
    weather_data_id bigserial NOT NULL,
    location_id bigint,
    record_time timestamp with time zone NOT NULL,
    data_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    temp_c numeric(4, 2),
    humidity integer,
    uv_index numeric(3, 1),
    wind_kph numeric(5, 2),
    raw_json jsonb,
    CONSTRAINT "WeatherData_pkey" PRIMARY KEY (weather_data_id),
    CONSTRAINT unique_location_time UNIQUE (location_id, record_time)
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_apscheduler_djangojob
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    next_run_time timestamp with time zone,
    job_state bytea NOT NULL,
    CONSTRAINT django_apscheduler_djangojob_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_apscheduler_djangojobexecution
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    run_time timestamp with time zone NOT NULL,
    duration numeric(15, 2),
    finished numeric(15, 2),
    exception character varying(1000) COLLATE pg_catalog."default",
    traceback text COLLATE pg_catalog."default",
    job_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_apscheduler_djangojobexecution_pkey PRIMARY KEY (id),
    CONSTRAINT unique_job_executions UNIQUE (job_id, run_time)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

ALTER TABLE IF EXISTS public."AdviceCache"
    ADD CONSTRAINT "AdviceCache_location_id_882fcbec_fk_Locations_location_id" FOREIGN KEY (location_id)
    REFERENCES public."Locations" (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "AdviceCache_location_id_882fcbec"
    ON public."AdviceCache"(location_id);


ALTER TABLE IF EXISTS public."DeviceTokens"
    ADD CONSTRAINT "DeviceTokens_user_id_15701fbe_fk_Users_user_id" FOREIGN KEY (user_id)
    REFERENCES public."Users" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "DeviceTokens_user_id_15701fbe"
    ON public."DeviceTokens"(user_id);


ALTER TABLE IF EXISTS public."ExtremeEvents"
    ADD CONSTRAINT "ExtremeEvents_location_id_fkey" FOREIGN KEY (location_id)
    REFERENCES public."Locations" (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_extremeevents_location_id
    ON public."ExtremeEvents"(location_id);


ALTER TABLE IF EXISTS public."LocationNotificationPreferences"
    ADD CONSTRAINT "LocationNotification_location_id_e2d0a297_fk_Locations" FOREIGN KEY (location_id)
    REFERENCES public."Locations" (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "LocationNotificationPreferences_location_id_e2d0a297"
    ON public."LocationNotificationPreferences"(location_id);


ALTER TABLE IF EXISTS public."LocationNotificationPreferences"
    ADD CONSTRAINT "LocationNotification_user_id_22d7bb49_fk_Users_use" FOREIGN KEY (user_id)
    REFERENCES public."Users" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "LocationNotificationPreferences_user_id_22d7bb49"
    ON public."LocationNotificationPreferences"(user_id);


ALTER TABLE IF EXISTS public."NotificationPreferences"
    ADD CONSTRAINT "NotificationPreferences_user_id_1f252454_fk_Users_user_id" FOREIGN KEY (user_id)
    REFERENCES public."Users" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "NotificationPreferences_user_id_1f252454"
    ON public."NotificationPreferences"(user_id);


ALTER TABLE IF EXISTS public."NotificationRecords"
    ADD CONSTRAINT "NotificationRecords_alert_id_8be5067b_fk_WeatherAlerts_alert_id" FOREIGN KEY (alert_id)
    REFERENCES public."WeatherAlerts" (alert_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "NotificationRecords_alert_id_8be5067b"
    ON public."NotificationRecords"(alert_id);


ALTER TABLE IF EXISTS public."NotificationRecords"
    ADD CONSTRAINT "NotificationRecords_location_id_57751510_fk_Locations" FOREIGN KEY (location_id)
    REFERENCES public."Locations" (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "NotificationRecords_location_id_57751510"
    ON public."NotificationRecords"(location_id);


ALTER TABLE IF EXISTS public."NotificationRecords"
    ADD CONSTRAINT "NotificationRecords_user_id_073eb59e_fk_Users_user_id" FOREIGN KEY (user_id)
    REFERENCES public."Users" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "NotificationRecords_user_id_073eb59e"
    ON public."NotificationRecords"(user_id);


ALTER TABLE IF EXISTS public."PreferenceAuditLogs"
    ADD CONSTRAINT "PreferenceAuditLogs_location_id_f78487ba_fk_Locations" FOREIGN KEY (location_id)
    REFERENCES public."Locations" (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "PreferenceAuditLogs_location_id_f78487ba"
    ON public."PreferenceAuditLogs"(location_id);


ALTER TABLE IF EXISTS public."PreferenceAuditLogs"
    ADD CONSTRAINT "PreferenceAuditLogs_user_id_08d5a8a1_fk_Users_user_id" FOREIGN KEY (user_id)
    REFERENCES public."Users" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "PreferenceAuditLogs_user_id_08d5a8a1"
    ON public."PreferenceAuditLogs"(user_id);


ALTER TABLE IF EXISTS public."QueuedNotifications"
    ADD CONSTRAINT "QueuedNotifications_location_id_6749d897_fk_Locations" FOREIGN KEY (location_id)
    REFERENCES public."Locations" (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "QueuedNotifications_location_id_6749d897"
    ON public."QueuedNotifications"(location_id);


ALTER TABLE IF EXISTS public."QueuedNotifications"
    ADD CONSTRAINT "QueuedNotifications_user_id_69428e7a_fk_Users_user_id" FOREIGN KEY (user_id)
    REFERENCES public."Users" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "QueuedNotifications_user_id_69428e7a"
    ON public."QueuedNotifications"(user_id);


ALTER TABLE IF EXISTS public."WeatherAlerts"
    ADD CONSTRAINT "WeatherAlerts_location_id_98dae208_fk_Locations_location_id" FOREIGN KEY (location_id)
    REFERENCES public."Locations" (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "WeatherAlerts_location_id_98dae208"
    ON public."WeatherAlerts"(location_id);


ALTER TABLE IF EXISTS public."WeatherData"
    ADD CONSTRAINT "WeatherData_location_id_fkey" FOREIGN KEY (location_id)
    REFERENCES public."Locations" (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.django_apscheduler_djangojobexecution
    ADD CONSTRAINT django_apscheduler_djangojobexecution_job_id_daf5090a_fk FOREIGN KEY (job_id)
    REFERENCES public.django_apscheduler_djangojob (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_apscheduler_djangojobexecution_job_id_daf5090a
    ON public.django_apscheduler_djangojobexecution(job_id);

END;