# Generated by Django 5.2.7 on 2025-10-22 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('users', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'db_table': '"Locations"',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '"Users"',
            },
        ),
        migrations.CreateModel(
            name='ExtremeEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('analysis_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(max_length=20)),
                ('impact_field', models.CharField(max_length=50)),
                ('forecast_details_vi', models.TextField()),
                ('actionable_advice_vi', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('raw_llm_json', models.JSONField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extreme_events', to='api.location')),
            ],
            options={
                'db_table': '"ExtremeEvents"',
                'indexes': [models.Index(fields=['location'], name='ExtremeEven_locatio_2906df_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('weather_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_time', models.DateTimeField()),
                ('data_type', models.CharField(max_length=20)),
                ('temp_c', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('uv_index', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('wind_kph', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('raw_json', models.JSONField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='api.location')),
            ],
            options={
                'db_table': '"WeatherData"',
                'indexes': [models.Index(fields=['record_time'], name='WeatherData_record__ab22c5_idx')],
                'unique_together': {('location', 'record_time')},
            },
        ),
    ]
