# Generated by Django 5.2.7 on 2025-10-29 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceCache',
            fields=[
                ('advice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('generated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('advice_type', models.CharField(max_length=10)),
                ('message_vi', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice_cache', to='api.location')),
            ],
            options={
                'db_table': '"AdviceCache"',
                'ordering': ['-generated_time'],
                'indexes': [models.Index(fields=['location', '-generated_time'], name='AdviceCache_locatio_5279de_idx')],
            },
        ),
    ]
