# Generated by Django 5.2.7 on 2025-11-22 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_advicecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='last_weather_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='last_weather_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('token_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='api.user')),
            ],
            options={
                'db_table': '"DeviceTokens"',
                'indexes': [models.Index(fields=['user', 'is_active'], name='DeviceToken_user_id_2a15c3_idx')],
            },
        ),
    ]
